# Generated by Django 5.1.5 on 2025-12-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('can_update_student', 'Can update student')]},
        ),
    ]
